version: "3.9"

services:
  app:
    image: thecodingmachine/php:7.4-v4-apache
    volumes: 
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - 8088:80
    environment:
      APACHE_DOCUMENT_ROOT: public/
      PHP_EXTENSION_XDEBUG: 0
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
